### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by zamazan4ik** [snowplow-incubator/snowplow-clickhouse-loader#1]
Hi!

What is the current state of this loader? As far as I see, some users (including me) are interested in uploading data into ClickHouse. E.g. this topic on Discourse: https://discourse.snowplow.io/t/upload-data-to-clickhouse/5976/2

I am curious - what are the current plans regarding ClickHouse support?

Thanks in advance!

**Comment by alexanderdean** [comment]
Paging @stanch

**Comment by stanch** [comment]
Hi @zamazan4ik, right now we are focusing on the next generation of data lake loaders (which would play better with data lake tooling, compared to our existing S3 and GCS loaders), and also on making the pipeline cloud-agnostic, so that we could run it in other clouds (e.g. Azure). Both are popular requests among our open source users and customers. Unfortunately, this means that we had to put the ClickHouse support on hold. We might pick it up later (e.g. next year), but at the moment this prototype is all we have, and it’s not “alive” :(
